### ISSUE TITLE
你好，当我在Windows下编译改代码一直报错

### ISSUE THREAD

**Issue by suichukeqi** [RongxuanTan/MP-MVS#2]
PatchMatch.cu(192): error : identifier "depth" is undefined

**Comment by RongxuanTan** [comment]
我查看了下PatchMatch.cu(192)但函数中我并没有找到 "depth"，可能我们之间的版本不对。
然后很抱歉，目前由于论文正在撰写中，我打算关闭这一项目直到我的论文发表。我的方法已经在ETH3D上进行评估，具体结果可以从ETH3D高分辨率排行榜上查看。。

**Comment by RongxuanTan** [comment]
我是在ubuntu下编译的，你也可以试试最新的代码
