### ISSUE TITLE
bug for building on linux

### ISSUE THREAD

**Issue by cv-lab-x** [RongxuanTan/MP-MVS#3]
`MP-MVS/src/utility.cpp:157:28: error: variable ‘std::fstream text_file’ has initializer but incomplete type
  157 |     std::fstream text_file(file_path, std::ios::in | std::ios::binary);`
Looking forward to you reply, may add some include files @RongxuanTan

**Comment by RongxuanTan** [comment]
The error occurred in the readColmapDmap function. You can try including the header file # include \<fstream>. If you do not have the need to read the depth map generated by Colmap, you can also solve this problem by commenting out this function.
